/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;
import java.util.regex.Matcher; 
import java.util.regex.Pattern; 
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author ari13
 */
public class AdminEditStudent extends javax.swing.JFrame {
    
    private boolean fetched_atleast_once = false;
    private int current_fetched_id = -1;
    private ArrayList<String> errors = new ArrayList<>();
    
    /**
     * Creates new form AdminEditStudent
     */
    public AdminEditStudent() {
        initComponents();
        
        // Set the username to the current sessions username
        adminToStudentText.setText("Hello," + CurrentSession.getUsername() + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leftPanel = new javax.swing.JPanel();
        iconUniversity = new javax.swing.JLabel();
        universityName = new javax.swing.JLabel();
        rightPanel = new javax.swing.JPanel();
        adminToStudentText = new javax.swing.JLabel();
        adminLoginText = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FatherName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MothersName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Phone = new javax.swing.JTextField();
        Address = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        DOB = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Gender = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        Citizenship = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        MaritalStatus = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        SubmitEditStudent = new javax.swing.JButton();
        addStudentSeparator = new javax.swing.JSeparator();
        editStudentSeparator = new javax.swing.JSeparator();
        assignStudentSeparator = new javax.swing.JSeparator();
        FetchID = new javax.swing.JTextField();
        FetchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));

        iconUniversity.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconUniversity.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/icons/icons8_university_campus_100px_1.png"))); // NOI18N
        iconUniversity.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        universityName.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        universityName.setForeground(new java.awt.Color(117, 97, 119));
        universityName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        universityName.setText("X - Y - Z University");

        rightPanel.setBackground(new java.awt.Color(49, 19, 51));
        rightPanel.setForeground(new java.awt.Color(255, 255, 255));
        addStudentSeparator.setVisible(false);
        editStudentSeparator.setVisible(false);
        assignStudentSeparator.setVisible(false);

        adminToStudentText.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        adminToStudentText.setForeground(new java.awt.Color(236, 240, 241));
        adminToStudentText.setText("Welcome, [USERNAME]");

        adminLoginText.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        adminLoginText.setForeground(new java.awt.Color(236, 240, 241));
        adminLoginText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/icons/icons8_database_administrator_21px.png"))); // NOI18N
        adminLoginText.setText("Edit Student");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Name");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fathers Name");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Mothers Name");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");

        Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Email");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Date Of Birth");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Gender");

        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Citizenship");

        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Marital Status");

        SubmitEditStudent.setText("Submit");
        SubmitEditStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SubmitEditStudentMouseClicked(evt);
            }
        });

        addStudentSeparator.setBackground(new java.awt.Color(49, 19, 51));
        addStudentSeparator.setForeground(new java.awt.Color(49, 19, 51));

        editStudentSeparator.setBackground(new java.awt.Color(49, 19, 51));
        editStudentSeparator.setForeground(new java.awt.Color(49, 19, 51));

        assignStudentSeparator.setBackground(new java.awt.Color(49, 19, 51));
        assignStudentSeparator.setForeground(new java.awt.Color(49, 19, 51));

        FetchButton.setText("Fetch");
        FetchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                FetchButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout rightPanelLayout = new javax.swing.GroupLayout(rightPanel);
        rightPanel.setLayout(rightPanelLayout);
        rightPanelLayout.setHorizontalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rightPanelLayout.createSequentialGroup()
                        .addComponent(adminLoginText, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(adminToStudentText, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, rightPanelLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(60, 60, 60)
                                        .addComponent(MothersName))
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(99, 99, 99)
                                        .addComponent(Phone))
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(92, 92, 92)
                                        .addComponent(Address))
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(105, 105, 105)
                                        .addComponent(Email))
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(67, 67, 67)
                                        .addComponent(DOB))
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(95, 95, 95)
                                        .addComponent(Gender))
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addGap(80, 80, 80)
                                        .addComponent(Citizenship))
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(65, 65, 65)
                                        .addComponent(MaritalStatus))
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(rightPanelLayout.createSequentialGroup()
                                        .addComponent(addStudentSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editStudentSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(167, 167, 167))))
                            .addGroup(rightPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rightPanelLayout.createSequentialGroup()
                                        .addComponent(FetchID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(FetchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SubmitEditStudent)))))
                        .addGap(38, 38, 38)
                        .addComponent(assignStudentSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        rightPanelLayout.setVerticalGroup(
            rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rightPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adminToStudentText, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(adminLoginText, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(FetchID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FetchButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(FatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(MothersName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(Phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Citizenship, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(MaritalStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(SubmitEditStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(rightPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addStudentSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editStudentSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignStudentSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(universityName, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addGroup(leftPanelLayout.createSequentialGroup()
                        .addComponent(iconUniversity, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGap(14, 14, 14)
                .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(iconUniversity, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(universityName, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                .addGap(244, 244, 244))
            .addComponent(rightPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailActionPerformed

    private void FetchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_FetchButtonMouseClicked
        String id_need_to_fetch = FetchID.getText();        
        try{
            conn c1 = new conn();
            
            String query = "SELECT * FROM student_profile WHERE id = '" + id_need_to_fetch + "'";
            ResultSet rs = c1.s.executeQuery(query);
            
            if(rs.next()){
                // Update All Fields with information of id=id_need_to_fetch
                fetch_all_fields_with_info_of(id_need_to_fetch);
                fetched_atleast_once = true;
                current_fetched_id = (int)Integer.parseInt(id_need_to_fetch);
            }else{
                JOptionPane.showMessageDialog(null, "No such student found with id=" + id_need_to_fetch + "!");
            }
            
        }catch(Exception ae){
             ae.printStackTrace();
        }
    }//GEN-LAST:event_FetchButtonMouseClicked

    private void SubmitEditStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitEditStudentMouseClicked
        if(fetched_atleast_once && current_fetched_id != -1){
            if(all_are_valid()){
                try{
                conn c1 = new conn();
                String query = "UPDATE student_profile " + 
                       "SET `Name`='" +Name.getText()+ "', `Fathers Name`='" +FatherName.getText()+ "', `Mothers Name`='" +MothersName.getText()+ "',"+
                        " `Phone`='" +Phone.getText()+ "', `Address`='" +Address.getText()+ "', `Email`='" +Email.getText()+ "',"+
                        " `Date of Birth`='" +DOB.getText()+ "', `Gender`='" +Gender.getText()+ "',"+
                        " `Citizenship`='" +Citizenship.getText()+ "', `Marital Status`='" +MaritalStatus.getText()+ "'"+
                        " WHERE `id`="+current_fetched_id+"";
                //JOptionPane.showMessageDialog(null, query);
                c1.s.executeUpdate(query);
                JOptionPane.showMessageDialog(null, "Successfully edited information of id="+current_fetched_id+"!");
                
                // Reset the Whole GUI
                current_fetched_id = -1;
                errors.clear();
                fetched_atleast_once = false;
                String EmptyStringTemplate = "";
                FetchID.setText(EmptyStringTemplate);
                Name.setText(EmptyStringTemplate);
                FatherName.setText(EmptyStringTemplate);
                MothersName.setText(EmptyStringTemplate);
                Phone.setText(EmptyStringTemplate);
                Address.setText(EmptyStringTemplate);
                Email.setText(EmptyStringTemplate);
                DOB.setText(EmptyStringTemplate);
                Gender.setText(EmptyStringTemplate);
                Citizenship.setText(EmptyStringTemplate);
                MaritalStatus.setText(EmptyStringTemplate);
                
                
            }catch(Exception ae){
                 ae.printStackTrace();
            }
            }else{
                // Throw error
                String errorMessage = "Error! Correctly fill the following fields: ";
                for (String s:errors) {
                    errorMessage = errorMessage + s + ",";
                }
                JOptionPane.showMessageDialog(null, errorMessage.substring(0, errorMessage.length() - 1));
            }
        }else{
            JOptionPane.showMessageDialog(null, "You need to fetch a student information using id and fetch button!");
        }
    }//GEN-LAST:event_SubmitEditStudentMouseClicked

    boolean all_are_valid(){
        String name = Name.getText();
        String fatherName = FatherName.getText();
        String mothersName = MothersName.getText();
        String phoneNo = Phone.getText();
        String address = Address.getText();
        String email = Email.getText();
        String dateOfBirth = DOB.getText();
        String gender = Gender.getText();
        String citizenship = Citizenship.getText();
        String maritalStatus = MaritalStatus.getText();
        boolean all_valid = true;
        errors.clear();
        if(!isValidName(name)){
            all_valid = false;
            errors.add("Name");
        }
        if(!isValidName(fatherName)){
            all_valid = false;
            errors.add("Fathers Name");
        }
        if(!isValidName(mothersName)){
            all_valid = false;
            errors.add("Mothers Name");
        }
        if(!isValidPhone(phoneNo)){
            all_valid = false;
            errors.add("Phone No");
        }
        if(!isValidName(address)){
            all_valid = false;
            errors.add("Address");
        }
        if(!isValidEmail(email)){
            all_valid = false;
            errors.add("Email");
        }
        if(!isValidDOB(dateOfBirth)){
            all_valid = false;
            errors.add("Date of Birth");
        }
        if(!isValidGender(gender)){
            all_valid = false;
            errors.add("Gender");
        }
        if(!isValidName(citizenship)){
            all_valid = false;
            errors.add("Citizenship");
        }
        if(!isValidName(maritalStatus)){
            all_valid = false;
            errors.add("Marital Status");
        }
        return all_valid;
    }
    
    void fetch_all_fields_with_info_of(String idx){
        int id = Integer.parseInt(idx);
        try{
            conn c1 = new conn();
            
            String query = "SELECT * FROM student_profile WHERE id = '" + id + "'";
            ResultSet rs = c1.s.executeQuery(query);
            rs.next();
           
            Name.setText(rs.getString("name"));
            FatherName.setText(rs.getString("Fathers Name"));
            MothersName.setText(rs.getString("Mothers Name"));
            Phone.setText(rs.getString("Phone"));
            Address.setText(rs.getString("Address"));
            Email.setText(rs.getString("Email"));
            DOB.setText(rs.getString("Date of Birth"));
            Gender.setText(rs.getString("Gender"));
            Citizenship.setText(rs.getString("Citizenship"));
            MaritalStatus.setText(rs.getString("Marital Status"));
            
            JOptionPane.showMessageDialog(null, "Successfully Fetched!");
            
        }catch(Exception ae){
             ae.printStackTrace();
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminEditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminEditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminEditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminEditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminEditStudent().setVisible(true);
            }
        });
    }
    
    public boolean isValidName(String name){
        return (name.length() > 0);
    }
    
    public boolean isValidPhone(String phone){
        return (phone.length() == 11);
    }
    
    public boolean isValidEmail(String email){
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."+ 
                            "[a-zA-Z0-9_+&*-]+)*@" + 
                            "(?:[a-zA-Z0-9-]+\\.)+[a-z" + 
                            "A-Z]{2,7}$"; 
        return ((Pattern.compile(emailRegex).matcher(email).matches()) && (email != null)); 
    }
    
    public boolean isValidDOB(String dob){
        for (int i = 0; i < dob.length(); i++) {
            if(!((dob.charAt(i) >= '0' && dob.charAt(i) <= '9') || dob.charAt(i) == '-') ) return false;            
        }
        return true;
    }
    
    public boolean isValidGender(String gender){
        return (gender.toUpperCase().equals("MALE") || gender.toUpperCase().equals("FEMALE"));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address;
    private javax.swing.JTextField Citizenship;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FatherName;
    private javax.swing.JButton FetchButton;
    private javax.swing.JTextField FetchID;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField MaritalStatus;
    private javax.swing.JTextField MothersName;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Phone;
    private javax.swing.JButton SubmitEditStudent;
    private javax.swing.JSeparator addStudentSeparator;
    private javax.swing.JLabel adminLoginText;
    private javax.swing.JLabel adminToStudentText;
    private javax.swing.JSeparator assignStudentSeparator;
    private javax.swing.JSeparator editStudentSeparator;
    private javax.swing.JLabel iconUniversity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JLabel universityName;
    // End of variables declaration//GEN-END:variables
}
